// I: Statistical Learning (135-154)
function sim135() { document.getElementById('simTag').textContent = 'Probability'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Quantify uncertainty</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">P(event) ∈ [0, 1]</div></div>'; }
function sim136() { document.getElementById('simTag').textContent = 'Bayes Theorem'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">P(A|B) = P(B|A)P(A)/P(B)</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Conditional probability</div></div>'; }
function sim137() { document.getElementById('simTag').textContent = 'Distribution'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Probability functions</p><button class="sim-btn" style="font-size:0.75rem">Normal</button><button class="sim-btn" style="font-size:0.75rem">Poisson</button><button class="sim-btn" style="font-size:0.75rem">Exponential</button></div>'; }
function sim138() { document.getElementById('simTag').textContent = 'MLE'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Maximum Likelihood Estimation</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Fit parameters to data</div></div>'; }
function sim139() { document.getElementById('simTag').textContent = 'Regression'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Predict continuous values</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">y = ax + b</div></div>'; }
function sim140() { document.getElementById('simTag').textContent = 'Classification'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Categorize into classes</p><button class="sim-btn">Logistic</button><button class="sim-btn">Naive Bayes</button></div>'; }
function sim141() { document.getElementById('simTag').textContent = 'Naive Bayes'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Simple probabilistic classifier</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Assumes independence</div></div>'; }
function sim142() { document.getElementById('simTag').textContent = 'SVM'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Support Vector Machine</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Maximum margin classifier</div></div>'; }
function sim143() { document.getElementById('simTag').textContent = 'Kernel Methods'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Map to high dimensions</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">RBF | Polynomial | Linear</div></div>'; }
function sim144() { document.getElementById('simTag').textContent = 'Clustering'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Group similar data</p><button class="sim-btn">K-means</button><button class="sim-btn">DBSCAN</button></div>'; }
function sim145() { document.getElementById('simTag').textContent = 'K-means'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Partitional clustering</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Centroid-based grouping</div></div>'; }
function sim146() { document.getElementById('simTag').textContent = 'GMM'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Gaussian Mixture Model</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Soft clustering</div></div>'; }
function sim147() { document.getElementById('simTag').textContent = 'HMM'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Hidden Markov Model</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Sequence modeling</div></div>'; }
function sim148() { document.getElementById('simTag').textContent = 'PCA'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Dimensionality Reduction</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Find principal components</div></div>'; }
function sim149() { document.getElementById('simTag').textContent = 'Feature Engineering'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Create useful features</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Domain knowledge</div></div>'; }
function sim150() { document.getElementById('simTag').textContent = 'Cross-Validation'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Evaluate model generalization</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">K-fold | Stratified</div></div>'; }
function sim151() { document.getElementById('simTag').textContent = 'Hyperparameter'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Model configuration</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Learning rate | Regularization</div></div>'; }
function sim152() { document.getElementById('simTag').textContent = 'Regularization'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Prevent overfitting</p><button class="sim-btn">L1</button><button class="sim-btn">L2</button><button class="sim-btn">Dropout</button></div>'; }
function sim153() { document.getElementById('simTag').textContent = 'Boosting'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Ensemble of weak learners</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">AdaBoost | Gradient Boosting</div></div>'; }
function sim154() { document.getElementById('simTag').textContent = 'Random Forest'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Ensemble of decision trees</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Bagging | Bootstrap</div></div>'; }

(function() {
  if (!window.SIM_MAP) window.SIM_MAP = {};
  for (let i = 135; i <= 154; i++) {
    const name = 'sim' + i;
    if (typeof window[name] === 'function') {
      window.SIM_MAP[i] = window[name];
    }
  }
})();




