// E: Data Structures & Algorithms (67-85)
function sim67() { document.getElementById('simTag').textContent = 'Array'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Contiguous memory locations</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px;font-family:monospace">[10, 20, 30, 40]<br>O(1) access by index</div></div>'; }
function sim68() { document.getElementById('simTag').textContent = 'Linked List'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Nodes with pointers</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">10 → 20 → 30 → null<br>O(n) access, O(1) insert</div></div>'; }
function sim69() { document.getElementById('simTag').textContent = 'Stack'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">LIFO: Last In First Out</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Push | Pop<br>Function calls, undo/redo</div></div>'; }
function sim70() { document.getElementById('simTag').textContent = 'Queue'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">FIFO: First In First Out</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Enqueue | Dequeue<br>Task scheduling, BFS</div></div>'; }
function sim71() { document.getElementById('simTag').textContent = 'Hash Table'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Key-value mapping with hashing</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">O(1) lookup average<br>Collision handling</div></div>'; }
function sim72() { document.getElementById('simTag').textContent = 'Binary Tree'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Hierarchical structure</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Root, left/right children<br>In-order, pre-order traversal</div></div>'; }
function sim73() { document.getElementById('simTag').textContent = 'BST'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Binary Search Tree</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Left < Root < Right<br>O(log n) search</div></div>'; }
function sim74() { document.getElementById('simTag').textContent = 'Heap'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Complete binary tree property</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Min-heap | Max-heap<br>Priority queue implementation</div></div>'; }
function sim75() { document.getElementById('simTag').textContent = 'Graph'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Vertices and edges</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Directed | Undirected<br>Weighted | Unweighted</div></div>'; }
function sim76() { document.getElementById('simTag').textContent = 'Search'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Finding elements</p><button class="sim-btn">Linear O(n)</button><button class="sim-btn">Binary O(logn)</button></div>'; }
function sim77() { document.getElementById('simTag').textContent = 'Sorting'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Arranging in order</p><button class="sim-btn">Bubble O(n²)</button><button class="sim-btn">Merge O(nlogn)</button><button class="sim-btn">Quick O(nlogn)</button></div>'; }
function sim78() { document.getElementById('simTag').textContent = 'BFS'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Breadth-First Search</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Level by level traversal<br>Uses queue</div></div>'; }
function sim79() { document.getElementById('simTag').textContent = 'DFS'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Depth-First Search</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Go deep before backtracking<br>Uses stack</div></div>'; }
function sim80() { document.getElementById('simTag').textContent = 'Dijkstra'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Shortest path algorithm</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Greedy approach<br>O((V+E)logV)</div></div>'; }
function sim81() { document.getElementById('simTag').textContent = 'DP'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Dynamic Programming</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Overlapping subproblems<br>Memoization | Tabulation</div></div>'; }
function sim82() { document.getElementById('simTag').textContent = 'Recursion'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Function calls itself</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px;font-family:monospace">factorial(n) = n * factorial(n-1)</div></div>'; }
function sim83() { document.getElementById('simTag').textContent = 'Backtracking'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Explore all possibilities</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">N-Queens | Sudoku solver</div></div>'; }
function sim84() { document.getElementById('simTag').textContent = 'Greedy'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Locally optimal choices</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Coin change | Activity selection</div></div>'; }
function sim85() { document.getElementById('simTag').textContent = 'NP-Complete'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Hardest problems in NP</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">TSP | SAT | Subset sum</div></div>'; }

(function() {
  if (!window.SIM_MAP) window.SIM_MAP = {};
  for (let i = 67; i <= 85; i++) {
    const name = 'sim' + i;
    if (typeof window[name] === 'function') {
      window.SIM_MAP[i] = window[name];
    }
  }
})();




