// Category g (100-114)

function sim100() { document.getElementById('simTag').textContent = 'Node 100'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 100\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim101() { document.getElementById('simTag').textContent = 'Node 101'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 101\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim102() { document.getElementById('simTag').textContent = 'Node 102'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 102\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim103() { document.getElementById('simTag').textContent = 'Node 103'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 103\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim104() { document.getElementById('simTag').textContent = 'Node 104'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 104\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim105() { document.getElementById('simTag').textContent = 'Node 105'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 105\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim106() { document.getElementById('simTag').textContent = 'Node 106'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 106\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim107() { document.getElementById('simTag').textContent = 'Node 107'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 107\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim108() { document.getElementById('simTag').textContent = 'Node 108'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 108\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim109() { document.getElementById('simTag').textContent = 'Node 109'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 109\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim110() { document.getElementById('simTag').textContent = 'Node 110'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 110\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim111() { document.getElementById('simTag').textContent = 'Node 111'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 111\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim112() { document.getElementById('simTag').textContent = 'Node 112'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 112\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim113() { document.getElementById('simTag').textContent = 'Node 113'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 113\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim114() { document.getElementById('simTag').textContent = 'Node 114'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 114\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }

(function() { if (!window.SIM_MAP) window.SIM_MAP = {}; for (let i = 100; i <= 114; i++) { const name = 'sim'+i; if (typeof window[name] === 'function') { window.SIM_MAP[i] = window[name]; } } })();
