// J: Deep Learning (155-174)
function sim155() { document.getElementById('simTag').textContent = 'Perceptron'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Single neuron classifier</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Σ(w*x) + b > threshold</div></div>'; }
function sim156() { document.getElementById('simTag').textContent = 'MLP'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Multi-Layer Perceptron</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Input → Hidden → Output</div></div>'; }
function sim157() { document.getElementById('simTag').textContent = 'Activation Function'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Introduces non-linearity</p><button class="sim-btn" style="font-size:0.75rem">ReLU</button><button class="sim-btn" style="font-size:0.75rem">Sigmoid</button><button class="sim-btn" style="font-size:0.75rem">Tanh</button></div>'; }
function sim158() { document.getElementById('simTag').textContent = 'Backpropagation'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Compute gradients efficiently</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Chain rule | Dynamic programming</div></div>'; }
function sim159() { document.getElementById('simTag').textContent = 'Gradient Descent'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Optimize weights</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">w ← w - α∇L</div></div>'; }
function sim160() { document.getElementById('simTag').textContent = 'Optimization'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Update strategies</p><button class="sim-btn" style="font-size:0.75rem">SGD</button><button class="sim-btn" style="font-size:0.75rem">Adam</button><button class="sim-btn" style="font-size:0.75rem">RMSprop</button></div>'; }
function sim161() { document.getElementById('simTag').textContent = 'CNN'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Convolutional Neural Network</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Convolution | Pooling | FC</div></div>'; }
function sim162() { document.getElementById('simTag').textContent = 'Convolution'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Filter responses</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Local feature detection</div></div>'; }
function sim163() { document.getElementById('simTag').textContent = 'Pooling'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Downsample</p><button class="sim-btn">MaxPool</button><button class="sim-btn">AvgPool</button></div>'; }
function sim164() { document.getElementById('simTag').textContent = 'RNN'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Recurrent Neural Network</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Sequence processing<br>Hidden state</div></div>'; }
function sim165() { document.getElementById('simTag').textContent = 'LSTM'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Long Short-Term Memory</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Gates: Input, Forget, Output</div></div>'; }
function sim166() { document.getElementById('simTag').textContent = 'GRU'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Gated Recurrent Unit</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Simpler than LSTM</div></div>'; }
function sim167() { document.getElementById('simTag').textContent = 'Attention'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Focus on relevant parts</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Query | Key | Value</div></div>'; }
function sim168() { document.getElementById('simTag').textContent = 'Transfer Learning'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Reuse pre-trained models</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Fine-tuning</div></div>'; }
function sim169() { document.getElementById('simTag').textContent = 'Data Augmentation'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Increase training data</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Rotation | Flip | Noise</div></div>'; }
function sim170() { document.getElementById('simTag').textContent = 'Batch Normalization'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Stabilize training</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Normalize activations</div></div>'; }
function sim171() { document.getElementById('simTag').textContent = 'Embedding'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Dense vector representation</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Word2Vec | GloVe</div></div>'; }
function sim172() { document.getElementById('simTag').textContent = 'Autoencoder'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Compress & reconstruct</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Encoder | Bottleneck | Decoder</div></div>'; }
function sim173() { document.getElementById('simTag').textContent = 'GAN'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Generative Adversarial Network</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Generator vs Discriminator</div></div>'; }
function sim174() { document.getElementById('simTag').textContent = 'VAE'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Variational Autoencoder</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Probabilistic generation</div></div>'; }

(function() {
  if (!window.SIM_MAP) window.SIM_MAP = {};
  for (let i = 155; i <= 174; i++) {
    const name = 'sim' + i;
    if (typeof window[name] === 'function') {
      window.SIM_MAP[i] = window[name];
    }
  }
})();




