// Category l (191-206)

function sim191() { document.getElementById('simTag').textContent = 'Node 191'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 191\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim192() { document.getElementById('simTag').textContent = 'Node 192'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 192\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim193() { document.getElementById('simTag').textContent = 'Node 193'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 193\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim194() { document.getElementById('simTag').textContent = 'Node 194'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 194\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim195() { document.getElementById('simTag').textContent = 'Node 195'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 195\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim196() { document.getElementById('simTag').textContent = 'Node 196'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 196\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim197() { document.getElementById('simTag').textContent = 'Node 197'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 197\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim198() { document.getElementById('simTag').textContent = 'Node 198'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 198\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim199() { document.getElementById('simTag').textContent = 'Node 199'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 199\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim200() { document.getElementById('simTag').textContent = 'Node 200'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 200\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim201() { document.getElementById('simTag').textContent = 'Node 201'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 201\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim202() { document.getElementById('simTag').textContent = 'Node 202'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 202\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim203() { document.getElementById('simTag').textContent = 'Node 203'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 203\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim204() { document.getElementById('simTag').textContent = 'Node 204'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 204\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim205() { document.getElementById('simTag').textContent = 'Node 205'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 205\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim206() { document.getElementById('simTag').textContent = 'Node 206'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 206\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }

(function() { if (!window.SIM_MAP) window.SIM_MAP = {}; for (let i = 191; i <= 206; i++) { const name = 'sim'+i; if (typeof window[name] === 'function') { window.SIM_MAP[i] = window[name]; } } })();
