// Category i (135-154)

function sim135() { document.getElementById('simTag').textContent = 'Node 135'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 135\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim136() { document.getElementById('simTag').textContent = 'Node 136'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 136\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim137() { document.getElementById('simTag').textContent = 'Node 137'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 137\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim138() { document.getElementById('simTag').textContent = 'Node 138'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 138\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim139() { document.getElementById('simTag').textContent = 'Node 139'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 139\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim140() { document.getElementById('simTag').textContent = 'Node 140'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 140\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim141() { document.getElementById('simTag').textContent = 'Node 141'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 141\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim142() { document.getElementById('simTag').textContent = 'Node 142'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 142\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim143() { document.getElementById('simTag').textContent = 'Node 143'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 143\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim144() { document.getElementById('simTag').textContent = 'Node 144'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 144\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim145() { document.getElementById('simTag').textContent = 'Node 145'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 145\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim146() { document.getElementById('simTag').textContent = 'Node 146'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 146\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim147() { document.getElementById('simTag').textContent = 'Node 147'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 147\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim148() { document.getElementById('simTag').textContent = 'Node 148'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 148\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim149() { document.getElementById('simTag').textContent = 'Node 149'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 149\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim150() { document.getElementById('simTag').textContent = 'Node 150'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 150\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim151() { document.getElementById('simTag').textContent = 'Node 151'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 151\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim152() { document.getElementById('simTag').textContent = 'Node 152'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 152\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim153() { document.getElementById('simTag').textContent = 'Node 153'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 153\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim154() { document.getElementById('simTag').textContent = 'Node 154'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 154\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }

(function() { if (!window.SIM_MAP) window.SIM_MAP = {}; for (let i = 135; i <= 154; i++) { const name = 'sim'+i; if (typeof window[name] === 'function') { window.SIM_MAP[i] = window[name]; } } })();
