// Category h (115-134)

function sim115() { document.getElementById('simTag').textContent = 'Node 115'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 115\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim116() { document.getElementById('simTag').textContent = 'Node 116'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 116\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim117() { document.getElementById('simTag').textContent = 'Node 117'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 117\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim118() { document.getElementById('simTag').textContent = 'Node 118'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 118\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim119() { document.getElementById('simTag').textContent = 'Node 119'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 119\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim120() { document.getElementById('simTag').textContent = 'Node 120'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 120\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim121() { document.getElementById('simTag').textContent = 'Node 121'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 121\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim122() { document.getElementById('simTag').textContent = 'Node 122'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 122\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim123() { document.getElementById('simTag').textContent = 'Node 123'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 123\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim124() { document.getElementById('simTag').textContent = 'Node 124'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 124\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim125() { document.getElementById('simTag').textContent = 'Node 125'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 125\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim126() { document.getElementById('simTag').textContent = 'Node 126'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 126\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim127() { document.getElementById('simTag').textContent = 'Node 127'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 127\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim128() { document.getElementById('simTag').textContent = 'Node 128'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 128\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim129() { document.getElementById('simTag').textContent = 'Node 129'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 129\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim130() { document.getElementById('simTag').textContent = 'Node 130'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 130\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim131() { document.getElementById('simTag').textContent = 'Node 131'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 131\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim132() { document.getElementById('simTag').textContent = 'Node 132'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 132\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim133() { document.getElementById('simTag').textContent = 'Node 133'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 133\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim134() { document.getElementById('simTag').textContent = 'Node 134'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 134\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }

(function() { if (!window.SIM_MAP) window.SIM_MAP = {}; for (let i = 115; i <= 134; i++) { const name = 'sim'+i; if (typeof window[name] === 'function') { window.SIM_MAP[i] = window[name]; } } })();
