// D: OS & Programming (50-66)
function sim50() { document.getElementById('simTag').textContent = 'Batch Processing'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Multiple jobs run sequentially</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Job1 → Job2 → Job3<br>No interaction during execution</div></div>'; }
function sim51() { document.getElementById('simTag').textContent = 'Multiprogramming'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Multiple programs in memory simultaneously</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">CPU time-sharing<br>Improves utilization</div></div>'; }
function sim52() { document.getElementById('simTag').textContent = 'Process'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Instance of a program in execution</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Code + Data + Stack<br>Process Control Block</div></div>'; }
function sim53() { document.getElementById('simTag').textContent = 'Scheduling'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">CPU decides which process runs</p><button class="sim-btn">FCFS</button><button class="sim-btn">SJF</button><button class="sim-btn">Round Robin</button><button class="sim-btn">Priority</button></div>'; }
function sim54() { document.getElementById('simTag').textContent = 'Virtual Memory'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Disk acts as extension of RAM</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Paging: divide into fixed pages<br>Swapping to disk</div></div>'; }
function sim55() { document.getElementById('simTag').textContent = 'Paging'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Virtual → Physical address mapping</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Page table lookup<br>TLB caching</div></div>'; }
function sim56() { document.getElementById('simTag').textContent = 'Segmentation'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Logical memory segments</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Code | Data | Heap | Stack</div></div>'; }
function sim57() { document.getElementById('simTag').textContent = 'Synchronization'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Coordinating concurrent processes</p><button class="sim-btn">Mutex</button><button class="sim-btn">Semaphore</button><button class="sim-btn">Lock</button></div>'; }
function sim58() { document.getElementById('simTag').textContent = 'Deadlock'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Circular wait for resources</p><div style="background:#ef444420;border:1px solid #ef4444;border-radius:10px;padding:15px">Process A waits for B<br>Process B waits for A</div></div>'; }
function sim59() { document.getElementById('simTag').textContent = 'File System'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Organizing data on disk</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Directories | Files | Inodes</div></div>'; }
function sim60() { document.getElementById('simTag').textContent = 'Machine Code'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">CPU-executable binary instructions</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px;font-family:monospace">10110000 01100001</div></div>'; }
function sim61() { document.getElementById('simTag').textContent = 'Assembly'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">1-to-1 mapping with machine code</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px;font-family:monospace">MOV ax, 61h<br>ADD ax, bx<br>JMP loop</div></div>'; }
function sim62() { document.getElementById('simTag').textContent = 'Compiler'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">High-level → Machine code</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px;font-family:monospace">Lexing → Parsing → Codegen</div></div>'; }
function sim63() { document.getElementById('simTag').textContent = 'Interpreter'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Executes code line-by-line</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Slower but more flexible<br>Easier debugging</div></div>'; }
function sim64() { document.getElementById('simTag').textContent = 'Variables'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Named memory locations</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px;font-family:monospace">x = 10<br>y = x + 5</div></div>'; }
function sim65() { document.getElementById('simTag').textContent = 'Functions'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Reusable code blocks</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px;font-family:monospace">def add(a, b):<br>    return a + b</div></div>'; }
function sim66() { document.getElementById('simTag').textContent = 'OOP'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Objects, classes, inheritance</p><button class="sim-btn">Class</button><button class="sim-btn">Inheritance</button><button class="sim-btn">Polymorphism</button></div>'; }

(function() {
  if (!window.SIM_MAP) window.SIM_MAP = {};
  for (let i = 50; i <= 66; i++) {
    const name = 'sim' + i;
    if (typeof window[name] === 'function') {
      window.SIM_MAP[i] = window[name];
    }
  }
})();




