// Category C: Logic & Computation (33-49)

function sim33() { document.getElementById('simTag').textContent = 'Boolean Logic'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Truth table for AND, OR, NOT</p><table style="width:100%;border-collapse:collapse;margin-top:10px"><tr style="background:var(--c)10"><th style="padding:8px;border:1px solid var(--border)">A</th><th style="padding:8px;border:1px solid var(--border)">B</th><th style="padding:8px;border:1px solid var(--border)">A∧B</th><th style="padding:8px;border:1px solid var(--border)">A∨B</th><th style="padding:8px;border:1px solid var(--border)">¬A</th></tr><tr><td style="padding:8px;border:1px solid var(--border)">0</td><td style="padding:8px;border:1px solid var(--border)">0</td><td style="padding:8px;border:1px solid var(--border)">0</td><td style="padding:8px;border:1px solid var(--border)">0</td><td style="padding:8px;border:1px solid var(--border)">1</td></tr><tr><td style="padding:8px;border:1px solid var(--border)">0</td><td style="padding:8px;border:1px solid var(--border)">1</td><td style="padding:8px;border:1px solid var(--border)">0</td><td style="padding:8px;border:1px solid var(--border)">1</td><td style="padding:8px;border:1px solid var(--border)">1</td></tr><tr><td style="padding:8px;border:1px solid var(--border)">1</td><td style="padding:8px;border:1px solid var(--border)">0</td><td style="padding:8px;border:1px solid var(--border)">0</td><td style="padding:8px;border:1px solid var(--border)">1</td><td style="padding:8px;border:1px solid var(--border)">0</td></tr><tr><td style="padding:8px;border:1px solid var(--border)">1</td><td style="padding:8px;border:1px solid var(--border)">1</td><td style="padding:8px;border:1px solid var(--border)">1</td><td style="padding:8px;border:1px solid var(--border)">1</td><td style="padding:8px;border:1px solid var(--border)">0</td></tr></table></div>'; }
function sim34() { document.getElementById('simTag').textContent = 'NAND/NOR Gates'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Universal gates: can build any logic</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">NAND = NOT(A AND B)<br>NOR = NOT(A OR B)</div></div>'; }
function sim35() { document.getElementById('simTag').textContent = 'Logic Circuits'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Combining gates into circuits</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px;font-family:monospace">Half Adder: Sum = A⊕B, Carry = A∧B</div></div>'; }
function sim36() { document.getElementById('simTag').textContent = 'Turing Machine'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Abstract model of universal computation</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Tape | Head | State machine | Rules</div></div>'; }
function sim37() { document.getElementById('simTag').textContent = 'Halting Problem'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Undecidable: no algorithm detects all non-halting programs</p><div style="background:#ef444420;border:1px solid #ef4444;border-radius:10px;padding:15px">Proof by contradiction shows impossibility</div></div>'; }
function sim38() { document.getElementById('simTag').textContent = 'P vs NP'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Fundamental open problem in CS</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px"><strong>P:</strong> Polynomial solvable<br><strong>NP:</strong> Polynomial verifiable<br>Worth \ million!</div></div>'; }
function sim39() { document.getElementById('simTag').textContent = 'Transistors'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Electronic switch: foundation of digital logic</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Billions on a chip<br>Switching time: nanoseconds</div></div>'; }
function sim40() { document.getElementById('simTag').textContent = 'Logic Gates'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Basic building blocks</p><div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin:10px 0"><button class="sim-btn">AND</button><button class="sim-btn">OR</button><button class="sim-btn">XOR</button><button class="sim-btn">NOT</button><button class="sim-btn">NAND</button><button class="sim-btn">NOR</button></div></div>'; }
function sim41() { document.getElementById('simTag').textContent = 'SR Flip-Flop'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Memory element storing one bit</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Set/Reset state<br>Stores 0 or 1</div></div>'; }
function sim42() { document.getElementById('simTag').textContent = 'Multiplexer'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Selector: routes one of N inputs to output</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Input: N lines + select code<br>Output: 1 line</div></div>'; }
function sim43() { document.getElementById('simTag').textContent = 'Decoder'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Binary input → one-hot output</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">2-in → 4-out decoder<br>Only one output active</div></div>'; }
function sim44() { document.getElementById('simTag').textContent = 'Full Adder'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Binary addition with carry</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Inputs: A, B, Carry_in<br>Outputs: Sum, Carry_out</div></div>'; }
function sim45() { document.getElementById('simTag').textContent = 'Multiplier'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Hardware binary multiplication</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Partial products + shifting<br>Wallace tree structure</div></div>'; }
function sim46() { document.getElementById('simTag').textContent = 'ALU'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Arithmetic & Logic Unit in CPU</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0"><button class="sim-btn">+ADD</button><button class="sim-btn">-SUB</button><button class="sim-btn">&AND</button><button class="sim-btn">|OR</button></div></div>'; }
function sim47() { document.getElementById('simTag').textContent = 'Memory'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Storage hierarchy: speed vs capacity</p><div style="margin:8px 0"><div style="border-left:4px solid #f97316;padding:6px">Registers: 1 ns</div><div style="border-left:4px solid #eab308;padding:6px">Cache: 10 ns</div><div style="border-left:4px solid #3b82f6;padding:6px">RAM: 100 ns</div></div></div>'; }
function sim48() { document.getElementById('simTag').textContent = 'CPU'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Fetch-Decode-Execute cycle</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px;font-family:monospace">1. Fetch instruction<br>2. Decode opcode<br>3. Execute<br>4. Store result</div></div>'; }
function sim49() { document.getElementById('simTag').textContent = 'ISA'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Instruction Set Architecture</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">LOAD, STORE, ADD, SUB, JUMP, BRANCH, CALL, RET</div></div>'; }

(function() {
  if (!window.SIM_MAP) window.SIM_MAP = {};
  for (let i = 33; i <= 49; i++) {
    const name = 'sim' + i;
    if (typeof window[name] === 'function') {
      window.SIM_MAP[i] = window[name];
    }
  }
})();



