// H: Classical AI (115-134)
function sim115() { document.getElementById('simTag').textContent = 'Symbolic AI'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Rule-based knowledge representation</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">IF-THEN rules | Logic</div></div>'; }
function sim116() { document.getElementById('simTag').textContent = 'Expert System'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Encodes human expertise</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Knowledge base | Inference engine</div></div>'; }
function sim117() { document.getElementById('simTag').textContent = 'Search'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Explore solution space</p><button class="sim-btn">BFS</button><button class="sim-btn">DFS</button><button class="sim-btn">A*</button></div>'; }
function sim118() { document.getElementById('simTag').textContent = 'Game Tree'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Minimax for game playing</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Max node | Min node<br>Chess, Go</div></div>'; }
function sim119() { document.getElementById('simTag').textContent = 'Alpha-Beta'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Prune game tree branches</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Reduce search space</div></div>'; }
function sim120() { document.getElementById('simTag').textContent = 'Heuristic'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Problem-specific guidance</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Estimate cost to goal</div></div>'; }
function sim121() { document.getElementById('simTag').textContent = 'Planning'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Find action sequences</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">STRIPS | PDDL | HTN</div></div>'; }
function sim122() { document.getElementById('simTag').textContent = 'Constraint Satisfaction'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Satisfy all constraints</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Variables | Domains | Constraints</div></div>'; }
function sim123() { document.getElementById('simTag').textContent = 'Backtracking'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Explore & undo</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">N-Queens | Sudoku</div></div>'; }
function sim124() { document.getElementById('simTag').textContent = 'Forward Chaining'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Start from facts → derive conclusions</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Bottom-up reasoning</div></div>'; }
function sim125() { document.getElementById('simTag').textContent = 'Backward Chaining'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Start from goal → find supporting facts</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Top-down reasoning</div></div>'; }
function sim126() { document.getElementById('simTag').textContent = 'Resolution'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Prove by contradiction</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15pt">CNF | Unification</div></div>'; }
function sim127() { document.getElementById('simTag').textContent = 'Fuzzy Logic'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Partial truth values</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Membership functions</div></div>'; }
function sim128() { document.getElementById('simTag').textContent = 'Ontology'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Formal knowledge structure</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Taxonomy | Relationships</div></div>'; }
function sim129() { document.getElementById('simTag').textContent = 'Semantic Web'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Machine-readable meanings</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">RDF | OWL | Linked Data</div></div>'; }
function sim130() { document.getElementById('simTag').textContent = 'Knowledge Graph'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Structured entity relationships</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Nodes = Entities | Edges = Relations</div></div>'; }
function sim131() { document.getElementById('simTag').textContent = 'Frame Logic'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Structured knowledge representation</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Slots | Attributes | Inheritance</div></div>'; }
function sim132() { document.getElementById('simTag').textContent = 'Bayesian Network'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Probabilistic graphical model</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Nodes = Variables | Edges = Dependencies</div></div>'; }
function sim133() { document.getElementById('simTag').textContent = 'Markov Network'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Undirected probabilistic graph</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Factor graphs</div></div>'; }
function sim134() { document.getElementById('simTag').textContent = 'Inference'; document.getElementById('simContainer').innerHTML = '<div style="padding:20px"><p class="sim-info">Compute probability distributions</p><div style="background:var(--c)10;border:1px solid var(--c)30;border-radius:10px;padding:15px">Exact | Approximate</div></div>'; }

(function() {
  if (!window.SIM_MAP) window.SIM_MAP = {};
  for (let i = 115; i <= 134; i++) {
    const name = 'sim' + i;
    if (typeof window[name] === 'function') {
      window.SIM_MAP[i] = window[name];
    }
  }
})();




