// Category j (155-174)

function sim155() { document.getElementById('simTag').textContent = 'Node 155'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 155\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim156() { document.getElementById('simTag').textContent = 'Node 156'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 156\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim157() { document.getElementById('simTag').textContent = 'Node 157'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 157\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim158() { document.getElementById('simTag').textContent = 'Node 158'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 158\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim159() { document.getElementById('simTag').textContent = 'Node 159'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 159\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim160() { document.getElementById('simTag').textContent = 'Node 160'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 160\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim161() { document.getElementById('simTag').textContent = 'Node 161'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 161\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim162() { document.getElementById('simTag').textContent = 'Node 162'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 162\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim163() { document.getElementById('simTag').textContent = 'Node 163'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 163\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim164() { document.getElementById('simTag').textContent = 'Node 164'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 164\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim165() { document.getElementById('simTag').textContent = 'Node 165'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 165\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim166() { document.getElementById('simTag').textContent = 'Node 166'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 166\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim167() { document.getElementById('simTag').textContent = 'Node 167'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 167\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim168() { document.getElementById('simTag').textContent = 'Node 168'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 168\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim169() { document.getElementById('simTag').textContent = 'Node 169'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 169\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim170() { document.getElementById('simTag').textContent = 'Node 170'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 170\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim171() { document.getElementById('simTag').textContent = 'Node 171'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 171\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim172() { document.getElementById('simTag').textContent = 'Node 172'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 172\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim173() { document.getElementById('simTag').textContent = 'Node 173'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 173\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }
function sim174() { document.getElementById('simTag').textContent = 'Node 174'; document.getElementById('simContainer').innerHTML = '<div style="padding:15px"><p class="sim-info">Interactive</p><button class="sim-btn" onclick="alert(\'Node 174\')">View</button><button class="sim-btn" onclick="location.reload()" style="margin-top:10px">Reset</button></div>'; }

(function() { if (!window.SIM_MAP) window.SIM_MAP = {}; for (let i = 155; i <= 174; i++) { const name = 'sim'+i; if (typeof window[name] === 'function') { window.SIM_MAP[i] = window[name]; } } })();
